 const SMPData = [
    {
        "allocation_id": 2242754,
        "allocated_qty": 3000,
        "used_qty": 0,
        "item_number": "SSV00S03116A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "tLK100",
        "partner_sfdc_account_id": "0016C00000hAsAoQAK",
        "partner_sfdc_account_name": "DAY WIRELESS SYSTEMS",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "TLK100",
        "package": "WAVE Two-Way Radio (Monthly)",
        "subsc_line_id": "300000020230226",
        "status": "Active",
        "start_date": "2023-02-07T00:00:00",
        "end_date": null,
        "promo_code": null,
        "promo_end_date": null
    },
    {
        "allocation_id": 2242755,
        "allocated_qty": 2000,
        "used_qty": 0,
        "item_number": "SSV00S03115A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "tLK100",
        "partner_sfdc_account_id": "0016C00000hAsAoQAK",
        "partner_sfdc_account_name": "DAY WIRELESS SYSTEMS",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "TLK100",
        "package": "WAVE Two-Way Radio And SafeGuard(Monthly)",
        "subsc_line_id": "300000020230227",
        "status": "Active",
        "start_date": "2023-02-07T00:00:00",
        "end_date": null,
        "promo_code": null,
        "promo_end_date": null
    },
    {
        "allocation_id": 2242756,
        "allocated_qty": 1000,
        "used_qty": 0,
        "item_number": "SSV00S03439A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "tLK110",
        "partner_sfdc_account_id": "0016C00000hAsAoQAK",
        "partner_sfdc_account_name": "DAY WIRELESS SYSTEMS",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "TLK110",
        "package": "WAVE PTX TLK110 Base Evergreen (Monthly)",
        "subsc_line_id": "300000020230228",
        "status": "Active",
        "start_date": "2023-02-07T00:00:00",
        "end_date": null,
        "promo_code": null,
        "promo_end_date": null
    },
    {
        "allocation_id": 2242757,
        "allocated_qty": 1000,
        "used_qty": 0,
        "item_number": "SSV00S03440A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "tLK110",
        "partner_sfdc_account_id": "0016C00000hAsAoQAK",
        "partner_sfdc_account_name": "DAY WIRELESS SYSTEMS",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "TLK110",
        "package": "WAVE PTX TLK110 SafeGuard Evergreen (Monthly)",
        "subsc_line_id": "300000020230229",
        "status": "Active",
        "start_date": "2023-02-07T00:00:00",
        "end_date": null,
        "promo_code": null,
        "promo_end_date": null
    },
    {
        "allocation_id": 2242758,
        "allocated_qty": 5000,
        "used_qty": 0,
        "item_number": "SSV00S03119A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "waveDispatchApp",
        "partner_sfdc_account_id": "0016C00000hAsAoQAK",
        "partner_sfdc_account_name": "DAY WIRELESS SYSTEMS",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "WAVEDISPATCH",
        "package": "WAVE LMR Interop Add On(Monthly)",
        "subsc_line_id": "300000020230235",
        "status": "Active",
        "start_date": "2023-02-07T00:00:00",
        "end_date": null,
        "promo_code": null,
        "promo_end_date": null
    },
    {
        "allocation_id": 2242759,
        "allocated_qty": 1000,
        "used_qty": 0,
        "item_number": "SSV00S03129A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "waveDispatchApp",
        "partner_sfdc_account_id": "0016C00000hAsAoQAK",
        "partner_sfdc_account_name": "DAY WIRELESS SYSTEMS",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "WAVEDISPATCH",
        "package": "WAVE Dispatch (Monthly)",
        "subsc_line_id": "300000020230236",
        "status": "Active",
        "start_date": "2023-02-07T00:00:00",
        "end_date": null,
        "promo_code": null,
        "promo_end_date": null
    },
    {
        "allocation_id": 2242760,
        "allocated_qty": 1000,
        "used_qty": 0,
        "item_number": "SSV00S03130A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "waveDispatchApp",
        "partner_sfdc_account_id": "0016C00000hAsAoQAK",
        "partner_sfdc_account_name": "DAY WIRELESS SYSTEMS",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "WAVEDISPATCH",
        "package": "WAVE Dispatch and SafeGuard (Monthly)",
        "subsc_line_id": "300000020230237",
        "status": "Active",
        "start_date": "2023-02-07T00:00:00",
        "end_date": null,
        "promo_code": null,
        "promo_end_date": null
    },
    {
        "allocation_id": 2242761,
        "allocated_qty": 2000,
        "used_qty": 0,
        "item_number": "SSV00S03131A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "waveDispatchApp",
        "partner_sfdc_account_id": "0016C00000hAsAoQAK",
        "partner_sfdc_account_name": "DAY WIRELESS SYSTEMS",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "WAVEDISPATCH",
        "package": "WAVE Dispatcher Streaming Video (Monthly)",
        "subsc_line_id": "300000020230238",
        "status": "Active",
        "start_date": "2023-02-07T00:00:00",
        "end_date": null,
        "promo_code": null,
        "promo_end_date": null
    },
    {
        "allocation_id": 2242762,
        "allocated_qty": 0,
        "used_qty": 0,
        "item_number": "SSV00S03126A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "waveMobileApp",
        "partner_sfdc_account_id": "0016C00000hAsAoQAK",
        "partner_sfdc_account_name": "DAY WIRELESS SYSTEMS",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "WAVEMOBILEAPP",
        "package": "WAVE Mobile App (Monthly)",
        "subsc_line_id": "300000010230263",
        "status": "Active",
        "start_date": "2023-02-09T00:00:00",
        "end_date": null,
        "promo_code": "",
        "promo_end_date": null
    },
    {
        "allocation_id": 2248763,
        "allocated_qty": 3000,
        "used_qty": 0,
        "item_number": "SSV00S03126A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "waveMobileApp",
        "partner_sfdc_account_id": "0016C00000hAsAoQAK",
        "partner_sfdc_account_name": "DAY WIRELESS SYSTEMS",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "WAVEMOBILEAPP",
        "package": "WAVE Mobile App (Monthly)",
        "subsc_line_id": "300000010230267",
        "status": "Active",
        "start_date": "2023-02-09T00:00:00",
        "end_date": null,
        "promo_code": "",
        "promo_end_date": null
    },
    {
        "allocation_id": 2248764,
        "allocated_qty": 2000,
        "used_qty": 0,
        "item_number": "SSV00S03127A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "waveMobileApp",
        "partner_sfdc_account_id": "0016C00000hAsAoQAK",
        "partner_sfdc_account_name": "DAY WIRELESS SYSTEMS",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "WAVEMOBILEAPP",
        "package": "WAVE Mobile App and SafeGuard (Monthly)",
        "subsc_line_id": "300000010230268",
        "status": "Active",
        "start_date": "2023-02-09T00:00:00",
        "end_date": null,
        "promo_code": "",
        "promo_end_date": null
    },
    {
        "allocation_id": 2248765,
        "allocated_qty": 5000,
        "used_qty": 0,
        "item_number": "SSV00S03128A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "waveMobileApp",
        "partner_sfdc_account_id": "0016C00000hAsAoQAK",
        "partner_sfdc_account_name": "DAY WIRELESS SYSTEMS",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "WAVEMOBILEAPP",
        "package": "WAVE Streaming Video (Monthly)",
        "subsc_line_id": "300000010230269",
        "status": "Active",
        "start_date": "2023-02-09T00:00:00",
        "end_date": null,
        "promo_code": "",
        "promo_end_date": null
    },
    {
        "allocation_id": 2238414,
        "allocated_qty": 0,
        "used_qty": 0,
        "item_number": "SSV00S03439A",
        "allocation_type": "INDIRECT",
        "cpqmodel": "tLK110",
        "partner_sfdc_account_id": "0016C00000k3npwQAA",
        "partner_sfdc_account_name": "CHICAGO COMMUNICATIONS LLC",
        "sfdc_account_id": "0016C00000nNpHwQAK",
        "sfdc_account_name": "WOCSIT FOUR",
        "app": "WOC",
        "offer": "TLK110",
        "package": "WAVE PTX TLK110 Base Evergreen (Monthly)",
        "subsc_line_id": "300000259963509",
        "status": "Active",
        "start_date": "2023-02-01T00:00:00",
        "end_date": null,
        "promo_code": "",
        "promo_end_date": null
    }
]


export default SMPData;
